apiVersion: apps/v1
kind: Deployment
metadata:
  name: okyes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okyes
  template:
    metadata:
      labels:
        app: okyes
    spec:
      containers:
      - image: okteto.dev/okyes:latest
        name: okyes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "54aa64b7-e0a4-4582-a024-e4d4133da546"
        - name: Vless_Path
          value: "/okone"
        - name: Vmess_UUID
          value: "54aa64b7-e0a4-4582-a024-e4d4133da546"
        - name: Vmess_Path
          value: "/okones"
        - name: Share_Path
          value: "/okoness"
